name: deploy

on: 
  push:
    branches: 
      - master

jobs:
  build-deploy:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: |
          yarn --registry=https://registry.npm.taobao.org
          yarn docs:build
          cp CNAME docs/.vuepress/dist/
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          ACTIONS_DEPLOY_KEY: ${{secrets.ACTIONS_DEPLOY_KEY}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: docs/.vuepress/dist