name: deploy

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: |
          yarn --registry=https://registry.npm.taobao.org
          yarn docs:build
          cp CNAME docs/.vuepress/dist/  

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - uses: peaceiris/actions-gh-pages@v3
        env:
          github_token: ${{secrets.BLOG_GITHUB_TOKEN}}
          publish_branch: gh-pages
          publish_dir: docs/.vuepress/dist